files_to_sync:
  - src: .distro/
    dest: ./
    delete: true
    filters:
      - "protect .git*"
      - "protect sources"
      - "protect changelog"
      - "protect gating.yaml"
  - .packit.yaml

upstream_package_name: scikit-build-core
specfile_path: .distro/python-scikit-build-core.spec
downstream_package_name: python-scikit-build-core
upstream_tag_template: v{version}

targets: &targets
  - fedora-all-x86_64
  - fedora-all-aarch64
  - epel-10-x86_64
  - epel-10-aarch64

_:
  # Job templates
  - &build-in-packit
    job: copr_build
  - &build-in-scikit-build
    <<: *build-in-packit
    owner: "@scikit-build"
  - &tests-downstream
    job: tests
    fmf_path: .distro
    identifier: downstream
  - &tests-upstream
    job: tests
    skip_build: true
    identifier: upstream
    targets:
      - fedora-development

jobs:
  # Upstream jobs
  - <<: *build-in-scikit-build
    trigger: release
    project: release
  - <<: *tests-downstream
    trigger: release
  - <<: *build-in-scikit-build
    trigger: commit
    branch: main
    project: nightly
  - <<: *tests-downstream
    trigger: commit
    branch: main
  - <<: *tests-upstream
    trigger: commit
    branch: main
  - <<: *build-in-packit
    trigger: pull_request
  - <<: *tests-downstream
    trigger: pull_request
  - <<: *tests-upstream
    trigger: pull_request
  # Downstream jobs
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
