# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: .distro/scikit-build-core.spec

files_to_sync:
  - src: .distro/scikit-build-core.spec
    dest: python-scikit-build-core.spec
  - .packit.yaml
  - src: .distro/python-scikit-build-core.rpmlintrc
    dest: python-scikit-build-core.rpmlintrc
upstream_package_name: scikit_build_core
downstream_package_name: python-scikit-build-core
update_release: false
upstream_tag_template: v{version}

jobs:
  - job: copr_build
    trigger: pull_request
    owner: "@scikit-build"
    project: scikit-build-core
    update_release: true
    release_suffix: "{PACKIT_RPMSPEC_RELEASE}"
    targets:
      - fedora-development
  - job: copr_build
    trigger: commit
    branch: main
    owner: "@scikit-build"
    project: nightly
    targets:
      - fedora-development-x86_64
      - fedora-latest-x86_64
      - fedora-development-aarch64
      - fedora-latest-aarch64
  - job: copr_build
    trigger: release
    owner: "@scikit-build"
    project: release
    targets:
      - fedora-development-x86_64
      - fedora-latest-x86_64
      - fedora-development-aarch64
      - fedora-latest-aarch64
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      # TODO: Switch to fedora-development and fedora-latest
      # There is an issue that the commits diverge on different PRs. In the meantime will create PRs on branched fedora
      # manually
      # https://github.com/packit/packit/issues/1724
      - fedora-rawhide
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
