name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - v[0123456789]*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

permissions: {}

jobs:
  lint:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install nox
        run: uv tool install nox
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: --all-files
      - name: Run PyLint
        run: nox -s pylint -- --output-format=github
      - name: Run nox generator
        run: |
          nox -t gen
          git diff --exit-code

  checks:
    name:
      🐍 ${{ matrix.python-version }} • CMake ${{ matrix.cmake-version }} on ${{
      matrix.runs-on }} ${{ matrix.architecture }}
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        python-version: ["pypy-3.11", "3.13", "3.14"]
        runs-on: [ubuntu-latest]
        cmake-version: ["3.15.x"]

        include:
          - python-version: "pypy-3.10"
            runs-on: windows-2022
            cmake-version: "3.21.x"
          - python-version: "3.11"
            runs-on: windows-2022
            cmake-version: "3.26.x"
          - python-version: "pypy-3.10"
            runs-on: ubuntu-latest
            cmake-version: "3.15.x"
          - python-version: "3.9"
            runs-on: ubuntu-latest
            cmake-version: "3.20.x"
          - python-version: "3.14t"
            runs-on: ubuntu-latest
            cmake-version: "4.2.x"

          - python-version: "pypy-3.10"
            runs-on: macos-latest
            cmake-version: "4.1.x"
          - python-version: "3.14t"
            runs-on: macos-latest
            cmake-version: "4.2.x"
          - python-version: "3.9"
            runs-on: macos-latest
            cmake-version: "3.21.x"
          - python-version: "3.10"
            runs-on: macos-15-intel
            cmake-version: "3.18.x"
          - python-version: "3.12"
            runs-on: macos-15-intel
            cmake-version: "3.29.x"
          - python-version: "3.10"
            runs-on: ubuntu-latest
            cmake-version: "3.22.x"
          - python-version: "3.11"
            runs-on: ubuntu-latest
            cmake-version: "3.26.x"
          - python-version: "3.9"
            runs-on: windows-2022
            cmake-version: "3.24.x"
          - python-version: "3.12"
            runs-on: windows-latest
            cmake-version: "3.26.x"
            architecture: x86
          - python-version: "3.14"
            runs-on: windows-latest
            cmake-version: "4.0.x"
          - python-version: "3.13"
            runs-on: windows-latest
            cmake-version: "3.26.x"
          - python-version: "3.9"
            runs-on: ubuntu-22.04
            cmake-version: "3.15.x"
          - python-version: "3.13"
            runs-on: ubuntu-24.04-arm
            cmake-version: "3.31.x"
          - python-version: "3.12"
            runs-on: windows-11-arm
            cmake-version: "4.0"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
          architecture: ${{ matrix.architecture }}

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Setup CMake ${{ matrix.cmake-version }}
        uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
        with:
          cmake-version: ${{ matrix.cmake-version }}

      - name: Install package (uv)
        run:
          uv pip install -e.[wheels,wheel-free-setuptools] --group=dev --system

      - name: Test package
        if: "!contains(matrix.python_version, 'pypy')"
        run: >-
          pytest -ra --showlocals --cov --cov-report=xml --cov-report=term -n
          auto --durations=20

      - name: Test package (two attempts)
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        if: "contains(matrix.python_version, 'pypy')"
        with:
          max_attempts: 2
          retry_on: error
          timeout_seconds: 5
          command: >-
            pytest -ra --showlocals --cov --cov-report=xml --cov-report=term
            --durations=20 -n auto

      - name: Upload coverage report
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          name:
            ${{ runner.os }}-${{ matrix.python-version }}-${{
            matrix.cmake-version }}
          verbose: true
          token: 6d9cc0e0-158a-41ee-b8f4-0318d3595ac2

  min:
    name: Min 🐍 ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.11"]
        # TODO: investigate failure with macos-latest (#1167)
        runs-on: [ubuntu-latest, macos-15-intel, windows-latest]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      # The min requirements are not compatible with some of the extra test
      # deps, so limit to just built-in deps.
      - name: Install extra helpers
        run: uv pip install ninja --system

      - name: Install min requirements
        run: |
          uv pip install -e. --group=test --group=test-schema --resolution=lowest-direct --system

      - name: Setup CMake 3.15
        uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
        if: runner.os != 'Windows'
        with:
          cmake-version: "3.15.x"

        # First version to support VS 17.0
      - name: Setup CMake 3.21
        uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
        if: runner.os == 'Windows'
        with:
          cmake-version: "3.21.x"

      - name: Show installed packages
        run: pip list

      - name: Test min package
        run: pytest -n auto -ra --showlocals -Wdefault

  manylinux:
    name: Manylinux on 🐍 3.14 • Free-threaded
    runs-on: ubuntu-latest
    timeout-minutes: 40
    container: quay.io/pypa/musllinux_1_2_x86_64@sha256:36bd94f44a613d006b5255f8393ab262d86a3bc016feedb91dc0b520a1b51e50 # 2026.05.17-1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Prepare venv
        run: python3.14t -m venv /venv

      - name: Install deps
        run: /venv/bin/pip install -e . --group=test ninja

      - name: Test package
        run: /venv/bin/pytest

  cygwin:
    name: Tests on 🐍 3.9 • cygwin
    runs-on: windows-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: cygwin/cygwin-install-action@711d29f3da23c9f4a1798e369a6f01198c13b11a # v6.1
        with:
          platform: x86_64
          packages:
            cmake ninja git make gcc-g++ python39 python39-devel python39-pip

      # Does not include test-numpy, since there are no wheels for this platform
      - name: Install
        run:
          python3.9 -m pip install . --group=test-core --group=test-pybind11
          --group=test-parallel --group=test-schema --group=test-meta

      - name: Test package
        run:
          python3.9 -m pytest -n auto -ra --showlocals -m "not virtualenv"
          --durations=20

  msys:
    name: Tests on 🐍 3 • msys UCRT
    runs-on: windows-latest
    timeout-minutes: 30

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@e9898307ac31d1a803454791be09ab9973336e1c # v2.31.1
        with:
          msystem: UCRT64
          path-type: minimal
          update: true
          install: >-
            base-devel git
          pacboy: >-
            python:p python-pip:p gcc:p cmake:p

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install
        run: python -m pip install . --group=test

      - name: Test package
        run: >-
          python -m pytest -n auto -ra --showlocals -m "not broken_on_urct"
          --durations=20

  mingw64:
    name: Tests on 🐍 3 • mingw64
    runs-on: windows-latest
    timeout-minutes: 30

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@e9898307ac31d1a803454791be09ab9973336e1c # v2.31.1
        with:
          msystem: mingw64
          path-type: minimal
          update: true
          install: >-
            base-devel git
          pacboy: >-
            python:p python-pip:p gcc:p cmake:p

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install
        run: python -m pip install . --group=test

      - name: Test package
        run: >-
          python -m pytest -n auto -ra --showlocals -m "not setuptools"
          --durations=20
        env:
          SETUPTOOLS_USE_DISTUTILS: "local"

  dist:
    name: Distribution build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: hynek/build-and-inspect-python-package@d44ca7d91762de7a7d5436ddae667c6da6d1c3df # v2.18.0

  docs:
    name: Docs on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest] # Windows command output issue (wrong Python selected)

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - uses: wntrblm/nox@97e345e6a26bb2c5aacff9cc4327bd4ac1b00ce6 # 2026.04.10
        with:
          python-versions: "3.12"

      - name: Linkcheck
        if: runner.os == 'Linux'
        run: nox -s docs -- -b linkcheck

      - name: Manpage
        run: nox -s docs -- -b man -W

      - name: Build docs with warnings as errors
        if: runner.os == 'Linux'
        run: nox -s docs -- -W

      - name: Check examples
        run: nox -s test_doc_examples

      - name: Verify no changes required to API docs
        run: |
          nox -s build_api_docs
          git diff --exit-code

  pass:
    name: CI pass
    if: always()
    needs: [lint, checks, min, cygwin, dist, docs]
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
